version: "3"
services:
  account-service:
    build: "account-service/"
    ports:
      - "3020:3000"
    environment:
      - "DATA_SERVICE=http://data-service:3000/graphql"
      - "SECRET=mysecret"
      - "PORT=3000"
    depends_on:
      - data-service
    networks:
      - some-net

  # communication-service:
  #   build: "communication-service/"
  #   ports:
  #     - "3010:3000"
  #   environment:
  #     - "PORT:3000"
  #     - "MQTT=mqtt://test.mosquitto.org"
  #     - "DATA_SERVICE=http://localhost:3040/graphql"

  # control-service:
  #   build: "control-service/"
  #   ports:
  #     - "3030:3000"
  #   environment:
  #     - "PORT=3000"
  #     - "DATA_SERVICE=http://localhost:3040/graphql"

  data-service:
    build: "data-service/"
    ports:
      - "3040:3000"
    environment:
      - "PORT=3000"
    networks:
      - some-net

  manager-service:
    build: "light-manager-service/"
    ports:
      - "3050:3000"
    environment:
      - "DATA_SERVICE=http://data-service:3000/graphql"
      - "ACCOUNT_SERVICE=http://account-service:3000"
      - "PORT=3000"
    depends_on:
      - data-service
      - account-service

networks:
  some-net:
    driver: bridge
